#!/usr/local/bin/bash

#здесь надо скопировать репу в /www/seogearbox.net.$branch
cd ../
rm -rf "/www/openhabr.net.$1"
cp -R "./openhabr.net.$1" /www/
cd  "/www/openhabr.net.$1"
mkdir logs
mkdir pids
mkdir build
# обновим модули ноды, вдруг что поменялось в package.json
npm install
#запустить gulp
gulp "$1"

#и растасовать результаты сборки
cp -R build/node ./
cp -R node_modules ./node/

cp -R build/static ./

./restart $1

exit
